#!/usr/bin/env bash
set -e

COMPOSE_FILE="docker/docker-compose.yml"
PROJECT="fastrag"
ENV_FILE=".env"

usage() {
    echo "Usage: ./manage.sh {config|build|start|update|stop|rm|log [service]}"
    echo ""
    echo "Commands:"
    echo "  config          Generate .env configuration file interactively"
    echo "  build           Build Docker images"
    echo "  start           Start all services"
    echo "  update          Rebuild and restart services"
    echo "  stop            Stop all services"
    echo "  rm              Stop and remove all services and volumes"
    echo "  log [service]   Follow logs (default: fastrag-app)"
    exit 1
}

# Python helper script for input handling
PYTHON_INPUT_HELPER='
import sys
prompt = sys.argv[1]
default = sys.argv[2] if len(sys.argv) > 2 else ""
try:
    if default:
        value = input(f"  {prompt} [{default}]: ")
    else:
        value = input(f"  {prompt}: ")
    print(value if value else default)
except EOFError:
    print(default)
'

# Prompt for a single variable: prompt_var PROMPT DEFAULT
# Reads user input; uses DEFAULT when input is empty.
# Falls back to Python if bash read fails.
prompt_var() {
    local prompt="$1"
    local default="$2"
    local input
    
    # Try bash read first
    if [ -t 0 ]; then
        if [ -n "$default" ]; then
            printf "  %s [%s]: " "$prompt" "$default"
        else
            printf "  %s: " "$prompt"
        fi
        if read -r input 2>/dev/null; then
            echo "${input:-$default}"
            return
        fi
    fi
    
    # Fallback to Python for input
    python3 -c "$PYTHON_INPUT_HELPER" "$prompt" "$default"
}

do_config() {
    echo "========================================="
    echo "  FastRAG Configuration Wizard"
    echo "========================================="
    echo ""

    if [ -f "$ENV_FILE" ]; then
        echo "  [!] .env file already exists."
        printf "  Overwrite? (y/N): "
        read -r confirm
        if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
            echo "  Aborted."
            exit 0
        fi
        echo ""
    fi

    echo "--- LLM / Embedding (OpenAI-compatible) ---"
    local api_key
    api_key=$(prompt_var "OpenAI API Key" "")
    local base_url
    base_url=$(prompt_var "OpenAI Base URL" "https://api.openai.com/v1")
    local llm_model
    llm_model=$(prompt_var "LLM Model" "gpt-4o-mini")
    local embedding_model
    embedding_model=$(prompt_var "Embedding Model" "text-embedding-3-small")
    local rerank_model
    rerank_model=$(prompt_var "Rerank Model (optional, press Enter to skip)" "")

    echo ""
    echo "--- Milvus Vector Store ---"
    local milvus_uri
    # Default to Docker service name when running inside compose
    milvus_uri=$(prompt_var "Milvus URI" "http://milvus:19530")

    echo ""
    echo "--- Timeouts ---"
    local llm_timeout
    llm_timeout=$(prompt_var "LLM Timeout (seconds)" "600")
    local llm_max_retries
    llm_max_retries=$(prompt_var "LLM Max Retries" "3")

    # Write .env
    cat > "$ENV_FILE" <<EOF
# FastRAG Configuration
# Generated by: ./manage.sh config

# LLM / Embedding (OpenAI-compatible)
FASTRAG_OPENAI_API_KEY=${api_key}
FASTRAG_OPENAI_BASE_URL=${base_url}
FASTRAG_LLM_MODEL=${llm_model}
FASTRAG_EMBEDDING_MODEL=${embedding_model}
FASTRAG_RERANK_MODEL=${rerank_model}

# Milvus Vector Store
# Milvus Standalone runs without authentication by default.
# Both containers share the same Docker network, so use the service name directly.
FASTRAG_MILVUS_URI=${milvus_uri}
FASTRAG_MILVUS_TOKEN=

# Timeouts
FASTRAG_LLM_TIMEOUT=${llm_timeout}
FASTRAG_LLM_MAX_RETRIES=${llm_max_retries}
EOF

    echo ""
    echo "========================================="
    echo "  .env file generated successfully!"
    echo "========================================="
    echo ""
    echo "  You can now run:"
    echo "    ./manage.sh build"
    echo "    ./manage.sh start"
}

if [ -z "$1" ]; then
    usage
fi

case "${1}" in
    config)
        do_config
        ;;
    build)
        docker compose -f "$COMPOSE_FILE" -p "$PROJECT" build
        echo "Build complete."
        ;;
    start)
        if [ ! -f "$ENV_FILE" ]; then
            echo "[!] .env file not found. Run './manage.sh config' first."
            exit 1
        fi
        docker compose -f "$COMPOSE_FILE" -p "$PROJECT" up -d
        echo "FastRAG started at http://localhost:8501"
        ;;
    update)
        docker compose -f "$COMPOSE_FILE" -p "$PROJECT" build
        docker compose -f "$COMPOSE_FILE" -p "$PROJECT" up -d
        echo "FastRAG updated and restarted at http://localhost:8501"
        ;;
    stop)
        docker compose -f "$COMPOSE_FILE" -p "$PROJECT" stop
        echo "FastRAG stopped."
        ;;
    rm)
        docker compose -f "$COMPOSE_FILE" -p "$PROJECT" down -v
        echo "FastRAG removed (containers + volumes)."
        ;;
    log)
        docker compose -f "$COMPOSE_FILE" -p "$PROJECT" logs -f "${2:-fastrag-app}"
        ;;
    *)
        usage
        ;;
esac
